# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
disqus: Daniel Solstad
google_analytics: UA-13093339-4
title: Daniel Solstad

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Daniel Solstad

description: Stylish Jekyll Theme
author:
  name: Daniel Solstad
  email: 
  github: dsolstad
  twitter: dsolstad
  pinterest: 
  linkedin: daniel-solstad-4b04ab87
  bio: Information security, life and stuff
  email_md5:
  avatar: https://raw.githubusercontent.com/dsolstad/dsolstad.github.io/main/images/avatar_clean_small.png

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
